import 'package:flutter/foundation.dart';

import 'package:biomonitoreoparticipativoapp/app/home/models/taxon.dart';

class Taxa with ChangeNotifier {
  List<Taxon> _items = [
    Taxon(
      id: '000001',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Panthera',
      specificEpithet: 'onca',
      scientificName: 'Panthera onca',
      scientificNameAuthorship: '(Linnaeus, 1758)',
      vernacularName: 'Jaguar',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Panthera_onca',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Junior-Jaguar-Belize-Zoo.jpg/198px-Junior-Jaguar-Belize-Zoo.jpg',
    ),
    Taxon(
      id: '000002',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Puma',
      specificEpithet: 'concolor',
      scientificName: 'Puma concolor',
      scientificNameAuthorship: '(Linnaeus, 1771)',
      vernacularName: 'Puma',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Puma_concolor',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Puma_concolor._Costa_Rica.jpg/320px-Puma_concolor._Costa_Rica.jpg',
    ),
    Taxon(
      id: '000003',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Leopardus',
      specificEpithet: 'pardalis',
      scientificName: 'Leopardus pardalis',
      scientificNameAuthorship: '(Linnaeus, 1758)',
      vernacularName: 'Ocelote, manigordo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Leopardus_pardalis',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg/312px-Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg',
    ),
    Taxon(
      id: '000004',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Puma',
      specificEpithet: 'yagouaroundi',
      scientificName: 'Puma yagouaroundi',
      scientificNameAuthorship: '(É.Geoffroy Saint-Hilaire, 1803)',
      vernacularName: 'Yaguarundi, león breñero',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Herpailurus_yagouaroundi',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Puma_yaguarondi.jpg/320px-Puma_yaguarondi.jpg',
    ),
    Taxon(
      id: '000005',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Leopardus',
      specificEpithet: 'tigrinus',
      scientificName: 'Leopardus tigrinus',
      scientificNameAuthorship: '(Schreber, 1775)',
      vernacularName: 'Oncilla, caucel',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Leopardus_tigrinus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Tika2009Jan24.jpg/225px-Tika2009Jan24.jpg',
    ),
    Taxon(
      id: '000006',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Carnivora',
      family: 'Felidae',
      genus: 'Leopardus',
      specificEpithet: 'wiedii',
      scientificName: 'Leopardus wiedii',
      scientificNameAuthorship: '(Schinz, 1821)',
      vernacularName: 'Tigrillo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Leopardus_wiedii',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Margaykat_Leopardus_wiedii.jpg/320px-Margaykat_Leopardus_wiedii.jpg',
    ),
    Taxon(
      id: '000007',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Tayassuidae',
      genus: 'Pecari',
      specificEpithet: 'tajacu',
      scientificName: 'Pecari tajacu',
      scientificNameAuthorship: '(Linnaeus, 1758)',
      vernacularName: 'Saíno, pecarí de collar',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Pecari_tajacu',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Collared_Peccary.jpg/301px-Collared_Peccary.jpg',
    ),
    Taxon(
      id: '000008',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Cervidae',
      genus: 'Mazama',
      specificEpithet: 'temama',
      scientificName: 'Mazama temama',
      scientificNameAuthorship: '(Kerr, 1792)',
      vernacularName: 'Cabro de monte',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Mazama_temama',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/5/59/Cabro_de_monte._Mazama_temama._Tapant%C3%AD._Costa_Rica.jpg',
    ),
    Taxon(
      id: '000009',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Artiodactyla',
      family: 'Cervidae',
      genus: 'Odocoileus',
      specificEpithet: 'virginianus',
      scientificName: 'Odocoileus virginianus',
      scientificNameAuthorship: '(Zimmermann, 1780)',
      vernacularName: 'Venado cola blanca',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Odocoileus_virginianus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/White-tailed_deer.jpg/316px-White-tailed_deer.jpg',
    ),
    Taxon(
      id: '000010',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Perissodactyla',
      family: 'Tapiridae',
      genus: 'Tapirus',
      specificEpithet: 'bairdii',
      scientificName: 'Tapirus bairdii',
      scientificNameAuthorship: '',
      vernacularName: 'Danta',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Tapirus_bairdii',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/7/7b/Central_American_Tapir-Belize20.jpg',
    ),
    Taxon(
      id: '000011',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Primates',
      family: 'Atelidae',
      genus: 'Alouatta',
      specificEpithet: 'palliata',
      scientificName: 'Alouatta palliata',
      scientificNameAuthorship: '(Gray, 1849)',
      vernacularName: 'Mono congo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Alouatta_palliata',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/c/c2/Allouataadulto_500px.jpg',
    ),
    Taxon(
      id: '000012',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Primates',
      family: 'Atelidae',
      genus: 'Ateles',
      specificEpithet: 'geoffroyi',
      scientificName: 'Ateles geoffroyi',
      scientificNameAuthorship: 'Kuhl, 1820',
      vernacularName: 'Mono araña',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Ateles_geoffroyi',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Panama_spider_monkey%2C_Costa_Rica.JPG/398px-Panama_spider_monkey%2C_Costa_Rica.JPG',
    ),
    Taxon(
      id: '000013',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Primates',
      family: 'Cebidae',
      genus: 'Cebus',
      specificEpithet: 'imitator',
      scientificName: 'Cebus imitator',
      scientificNameAuthorship: 'Thomas, 1903',
      vernacularName: 'Mono cara blanca',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Cebus_capucinus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Capuchin_Costa_Rica.jpg/245px-Capuchin_Costa_Rica.jpg',
    ),
    Taxon(
      id: '000014',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Primates',
      family: 'Cebidae',
      genus: 'Saimiri',
      specificEpithet: 'oerstedii',
      scientificName: 'Saimiri oerstedii',
      scientificNameAuthorship: '(Reinhardt, 1872)',
      vernacularName: 'Mono tití',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Saimiri_oerstedii',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Mono_Titi_Saimiri_Oerstedii_P_N_Manuel_Antonio.JPG/275px-Mono_Titi_Saimiri_Oerstedii_P_N_Manuel_Antonio.JPG',
    ),
    Taxon(
      id: '000015',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Rodentia',
      family: 'Dasyproctidae',
      genus: 'Dasyprocta',
      specificEpithet: 'punctata',
      scientificName: 'Dasyprocta punctata',
      scientificNameAuthorship: 'Gray, 1842',
      vernacularName: 'Cherenga, guatusa',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Dasyprocta_punctata',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Dasyprocta_punctata_%28Gamboa%2C_Panama%29.jpg/320px-Dasyprocta_punctata_%28Gamboa%2C_Panama%29.jpg',
    ),
    Taxon(
      id: '000016',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Mammalia',
      order: 'Rodentia',
      family: 'Cuniculidae',
      genus: 'Cuniculus',
      specificEpithet: 'paca',
      scientificName: 'Cuniculus paca',
      scientificNameAuthorship: '(Linnaeus, 1766)',
      vernacularName: 'Tepezcuintle',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Cuniculus_paca',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Cuniculus_paca.jpg/320px-Cuniculus_paca.jpg',
    ),
    Taxon(
      id: '000017',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Pharomachrus',
      specificEpithet: 'mocinno',
      scientificName: 'Pharomachrus mocinno',
      scientificNameAuthorship: 'De la Llave, 1832',
      vernacularName: 'Quetzal',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Pharomachrus_mocinno',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Pharomachrus_mocinno_Monteverde_10.jpg/320px-Pharomachrus_mocinno_Monteverde_10.jpg',
    ),
    Taxon(
      id: '000018',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Trogon',
      specificEpithet: 'rufus',
      scientificName: 'Trogon rufus',
      scientificNameAuthorship: 'Gmelin, 1788',
      vernacularName: 'Trogón cabeciverde',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Trogon_rufus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Black-throated_Trogon_1.jpeg/320px-Black-throated_Trogon_1.jpeg',
    ),
    Taxon(
      id: '000019',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Trogon',
      specificEpithet: 'bairdii',
      scientificName: 'Trogon bairdii',
      scientificNameAuthorship: 'Lawrence, 1868',
      vernacularName: 'Trogón vientribermejo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Trogon_bairdii',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Trogon_de_Baird.jpg/320px-Trogon_de_Baird.jpg',
    ),
    Taxon(
      id: '000020',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Trogon',
      specificEpithet: 'caligatus',
      scientificName:
          'Trogon caligatus', // ¿Será Trogon violaceus caligatus Gould, 1838?
      scientificNameAuthorship: '',
      vernacularName: 'Trogón cabecimorado',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Trogon_caligatus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Gartered_Trogon_%28Trogon_caligatus%29_%287222812684%29.jpg/320px-Gartered_Trogon_%28Trogon_caligatus%29_%287222812684%29.jpg',
    ),
    Taxon(
      id: '000021',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Trogon',
      specificEpithet: 'massena',
      scientificName: 'Trogon massena',
      scientificNameAuthorship: 'Gould, 1838',
      vernacularName: 'Trogón coliplomizo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Trogon_massena',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Slaty-tailed_Trogon_%28Trogon_massena%29_%287222810824%29.jpg/320px-Slaty-tailed_Trogon_%28Trogon_massena%29_%287222810824%29.jpg',
    ),
    Taxon(
      id: '000022',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Trogoniformes',
      family: 'Trogonidae',
      genus: 'Trogon',
      specificEpithet: 'collaris',
      scientificName: 'Trogon collaris',
      scientificNameAuthorship: 'Vieillot, 1817',
      vernacularName: 'Trogón collarejo',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Trogon_collaris',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Trogon_collaris_%28Trog%C3%B3n_collarejo%29_%2814981909907%29.jpg/320px-Trogon_collaris_%28Trog%C3%B3n_collarejo%29_%2814981909907%29.jpg',
    ),
    Taxon(
      id: '000023',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Passeriformes',
      family: 'Cotingidae',
      genus: 'Procnias',
      specificEpithet: 'tricarunculatus',
      scientificName: 'Procnias tricarunculatus',
      scientificNameAuthorship: '(J.Verreaux & E.Verreaux, 1853)',
      vernacularName: 'Pájaro campana',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Procnias_tricarunculatus',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Procnias_tricarunculata_-Costa_Rica_-male-8-4c.jpg/257px-Procnias_tricarunculata_-Costa_Rica_-male-8-4c.jpg',
    ),
    Taxon(
      id: '000024',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Passeriformes',
      family: 'Turdidae',
      genus: 'Myadestes',
      specificEpithet: 'melanops',
      scientificName: 'Myadestes melanops',
      scientificNameAuthorship: 'Salvin, 1865',
      vernacularName: 'Jilguero',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Myadestes_melanops',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Myadestes_melanops.jpg/320px-Myadestes_melanops.jpg',
    ),
    Taxon(
      id: '000025',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Tinamiformes',
      family: 'Tinamidae',
      genus: 'Tinamus',
      specificEpithet: 'major',
      scientificName: 'Tinamus major',
      scientificNameAuthorship: '(J.F.Gmelin, 1789)',
      vernacularName: 'Gallina de monte, tinamú grande',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Tinamus_major',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/b/b1/Tinamus_majorPCSL00504B.jpg',
    ),
    Taxon(
      id: '000026',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Tinamiformes',
      family: 'Tinamidae',
      genus: 'Nothocercus',
      specificEpithet: 'bonapartei',
      scientificName: 'Nothocercus bonapartei',
      scientificNameAuthorship: '(G.R.Gray, 1867)',
      vernacularName: 'Gallina de monte, tinamú serrano',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Nothocercus_bonapartei',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Nothocercus_bonapartei_1902.jpg/284px-Nothocercus_bonapartei_1902.jpg',
    ),
    Taxon(
      id: '000027',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Tinamiformes',
      family: 'Tinamidae',
      genus: 'Crypturellus',
      specificEpithet: 'soui',
      scientificName: 'Crypturellus soui',
      scientificNameAuthorship: '(Hermann, 1783)',
      vernacularName: 'Gallina de monte, tinamú chico',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Crypturellus_soui',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Little_Tinamou_-_Rio_Tigre_-_Costa_Rica_S4E9970_%2826604325872%29.jpg/800px-Little_Tinamou_-_Rio_Tigre_-_Costa_Rica_S4E9970_%2826604325872%29.jpg',
    ),
    Taxon(
      id: '000028',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Galliformes',
      family: 'Cracidae',
      genus: 'Crax',
      specificEpithet: 'rubra',
      scientificName: 'Crax rubra',
      scientificNameAuthorship: 'Linnaeus, 1758',
      vernacularName: 'Pavón grande',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Crax_rubra',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/6/6a/Crax_rubra_%28Great_Curassow%29_-_male.jpg',
    ),
    Taxon(
      id: '000029',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Galliformes',
      family: 'Cracidae',
      genus: 'Penelope',
      specificEpithet: 'purpurascens',
      scientificName: 'Penelope purpurascens',
      scientificNameAuthorship: 'Wagler, 1830',
      vernacularName: 'Pava granadera',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Penelope_purpurascens',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Crested_Guan_%2849667610346%29.jpg/320px-Crested_Guan_%2849667610346%29.jpg',
    ),
    Taxon(
      id: '000030',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Galliformes',
      family: 'Cracidae',
      genus: 'Ortalis',
      specificEpithet: 'cinereiceps',
      scientificName: 'Ortalis cinereiceps',
      scientificNameAuthorship: 'G.R.Gray, 1867',
      vernacularName: 'Pajuila, chachalaca cabecigrís',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Ortalis_cinereiceps',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Gray-headed_Chachalaca_%286901564788%29.jpg/320px-Gray-headed_Chachalaca_%286901564788%29.jpg',
    ),
    Taxon(
      id: '000031',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Aves',
      order: 'Galliformes',
      family: 'Cracidae',
      genus: 'Chamaepetes',
      specificEpithet: 'unicolor',
      scientificName: 'Chamaepetes unicolor',
      scientificNameAuthorship: 'Salvin, 1867',
      vernacularName: 'Pava negra',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Chamaepetes_unicolor',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Black_guan_Bosque_de_Paz.JPG/320px-Black_guan_Bosque_de_Paz.JPG',
    ),
    Taxon(
      id: '000032',
      kingdom: 'Animalia',
      phylum: 'Chordata',
      class_: 'Amphibia',
      order: 'Anura',
      family: 'Bufonidae',
      genus: 'Atelopus',
      specificEpithet: 'varius',
      scientificName: 'Atelopus varius',
      scientificNameAuthorship: '(Lichtenstein & Martens, 1856)',
      vernacularName: 'Rana arlequín',
      taxonRank: 'species',
      urlSpeciesPage: 'https://es.wikipedia.org/wiki/Atelopus_varius',
      urlImage:
          'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Atelopus_varius.jpg/320px-Atelopus_varius.jpg',
    ),
  ];

  List<Taxon> get items {
    return [..._items];
  }

  Taxon findById(String id) {
    return _items.firstWhere(
      (taxon) => taxon.id == id,
    );
  }
}
